### ISSUE TITLE
As a developer, I want to mock Graph responses to test my integration with the Microsoft Graph client SDK

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-design#26]
I should be able to:

* I should be able to mark a request as using the TestHandler and be able to provide HttpResponseMessage values (body, headers) when creating the request. 
* Use an out of box GraphTestHandler that provides a way for me to indicate that a request should be responded to by the test handler. 
* A Http header trigger to turn on the test handler.
* Map URLs and headers to test handler registered responses

**Comment by mgwojciech** [comment]
Hi Michael,
I just blogged about it (You can implement Your own IHttpProvider and pass it to GraphServiceClient).
Here is the link, hope it will help:
https://mgwdevcom.wordpress.com/2020/11/03/unit-testing-with-graph-sdk/

**Comment by MIchaelMainer** [comment]
@mgwojciech Thank you for sharing that useful solution for this story!

**Comment by profsmallpine** [comment]
Any guidance or snippets for testing in go. Tried ye old:

```
        server := httptest.NewServer(nil)
        server.Config.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("we made it into the config handler")
	})
        ...
        adapter.SetBaseUrl(server.URL)
        client := msgraphsdk.NewGraphServiceClient(adapter)
        client.DoThing()
```

Sadly, I get `url scheme must be https`

**Comment by MIchaelMainer** [comment]
I defer to @baywet about whether the https scheme requirement can be overridden by. 

Take a look at [https://github.com/microsoftgraph/msgraph-developer-proxy](msgraph-developer-proxy) as that may help you while testing.

**Comment by baywet** [comment]
The https requirement come from [the access token provide](https://github.com/microsoft/kiota-authentication-azure-go/blob/4a4ba1ca9113f495de0fc8802997d048722971c2/azure_identity_access_token_provider.go#L83)
Effectively we don't ever want to risk transmitting an access token over clear HTTP for obvious security reasons.

I think there are two set of test types that are valuable for apps integrating with Microsoft Graph at this level:

- unit tests: those should be focused on the application logic and NOT on the integration of Microsoft Graph itself. The integration point with Microsoft Graph should be encapsulated in a service which should be mocked for that purpose. Not only it'll run faster, but also it creates a good separation of concerns.
- integration tests: making sure the integration with Microsoft Graph encapsulated by the service I was mentioning earlier is transmitting the right information. That should be run less often because slower, and costlier to setup, and should be run against a mock service to avoid having to implement manually things like transient errors etc... And yes, the developer proxy can help greatly with that aspect.

Having to mock the http responses is time consuming and this is something we (Microsoft) are responsible for to test aspects like retry handling, redirect handling, serialization/deserialization, url building, etc... I don't believe you should be paying that cost since it's part of the value proposition of the SDK.

**Comment by baywet** [comment]
Closing since there are now follow ups to this one.
