### ISSUE TITLE
should v1 also be in the telemetry header?

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-design#63]
Hey @MIchaelMainer 
Starting a discussion about a specific point I missed when I reviewed #61

I'm arguing here for the following change

```diff
| Client SDK Library Component | Template | Example |
| --- | --- | --- |
| **Core** | `graph-{lang}-core/{major}.{minor}.{build}` | `graph-dotnet-core/1.16.0` |
-| **v1.0 Service Model** | `graph-{lang}/{major}.{minor}.{build}` | `graph-dotnet/1.16.0` |
+| **v1.0 Service Model** | `graph-{lang}-v1.0/{major}.{minor}.{build}` | `graph-dotnet/1.16.0` |
| **Beta Service Model** | `graph-{lang}-beta/{major}.{minor}.{build}` | `graph-dotnet-beta/1.16.0` |
```

Reasoning being:
- consistent behavior (between beta and v1)
- anticipates an eventual v2

Drawbacks:
- more updates required
- we'll have a bunch of outdated clients sending the wrong thing

Thoughts?

**Comment by MIchaelMainer** [comment]
@baywet You make a good point. We already will need to make changes to the SdkVersion header values so we should include this as well.  We already have clients sending different values so this will won't be a dramatic change.

**Comment by MIchaelMainer** [comment]
After more thought, I'd like to not make this change now for existing v1.0 libraries, but specify in the telemetry design document that any **new** endpoint-based component/library must specify the endpoint it targets in the SdkVersion header.

**Comment by baywet** [comment]
grand fathering existing service libs is only going to prolong the suffering of having to deal with two formats. I do agree with making one salvo of changes, and little by little people will migrate to newer versions of the libs and send the newer telemetry header. Taking a tiered approach will only make the telemetry processing team's work more difficult.

**Comment by MIchaelMainer** [comment]
I'm not sure about the suffering part as long as we are consistent. I'll have a conversation with the data team to get their input before moving on this.

**Comment by MIchaelMainer** [comment]
It won't make a difference to leave the v1.0 token off for telemetry purposes as we can already determine the service endpoint in our telemetry data. Keeping the v1.0 service library naming as is maintains consistency for our current service libraries and keeps them in sync with our repo naming convention for v1.0 service libraries. 

Changing it now would then require aggregation across multiple values for v1.0 Java and .NET. Not much of a deal, but another consideration.

Since we are already consistent across the service libraries (Java and .NET), I think we should keep as is for future service libraries that will target v1.0. 

Please reopen if you strongly disagree.

**Comment by baywet** [comment]
not strong opinion here, thanks for going through the discussion!
opening an issue on go sdk to conform.
